// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZAg3OH6t_ya6Lcay47itJvNIpu6E8tZI',
    appId: '1:1006392222454:web:c80b4726cc885aab6d02d7',
    messagingSenderId: '1006392222454',
    projectId: 'webtoon-b7b3e',
    authDomain: 'webtoon-b7b3e.firebaseapp.com',
    storageBucket: 'webtoon-b7b3e.appspot.com',
    measurementId: 'G-30VQR89KXF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvUuNCmDjFHwi-t7me6lKFzmr6t9y4s2w',
    appId: '1:1006392222454:android:8f5d5f5bc299d0526d02d7',
    messagingSenderId: '1006392222454',
    projectId: 'webtoon-b7b3e',
    storageBucket: 'webtoon-b7b3e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcJxwlhGo3Hq5LRxjHxi__EKT1LCfjYMM',
    appId: '1:1006392222454:ios:5f5a87549a1f28e16d02d7',
    messagingSenderId: '1006392222454',
    projectId: 'webtoon-b7b3e',
    storageBucket: 'webtoon-b7b3e.appspot.com',
    iosBundleId: 'com.example.webtoon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcJxwlhGo3Hq5LRxjHxi__EKT1LCfjYMM',
    appId: '1:1006392222454:ios:54095e45a36e5cb56d02d7',
    messagingSenderId: '1006392222454',
    projectId: 'webtoon-b7b3e',
    storageBucket: 'webtoon-b7b3e.appspot.com',
    iosBundleId: 'com.example.webtoon.RunnerTests',
  );
}
